apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ocitutorials-preview-ingress
  namespace: paasdocs-preview
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: paasdocs-preview-auth-secret
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - paasdocs'
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: ocitutorials-preview
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ocitutorials-preview
  namespace: paasdocs-preview
spec:
  selector:
    app: ocitutorials-preview
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocitutorials-preview
  namespace: paasdocs-preview
  labels:
    app: ocitutorials-preview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocitutorials-preview
  template:
    metadata:
      labels:
        app: ocitutorials-preview
    spec:
      containers:
      - name: ocitutorials-preview
        image: nrt.ocir.io/orasejapan/paasdocs/paasdocs-preview:@@IMAGE_TAG@@
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: paasdocs-preview-image-pull-secret