apiVersion: v1
kind: Service
metadata:
  name: ocitutorials-preview
  namespace: paasdocs-preview
spec:
  selector:
    app: ocitutorials-preview
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocitutorials-preview
  namespace: paasdocs-preview
  labels:
    app: ocitutorials-preview
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ocitutorials-preview
  template:
    metadata:
      labels:
        app: ocitutorials-preview
    spec:
      containers:
      - name: ocitutorials-preview
        image: nrt.ocir.io/orasejapan/oci-tutorials-improve/staging-env:${BUILDRUN_HASH}
        ports:
        - protocol: TCP
          containerPort: 4001
      imagePullSecrets:
      - name: paasdocs-preview-image-pull-secret