reviewers:
  
files:
  'tutorials/**':
    - tniita
    - cyberblack28
    - mmarukaw
    - oraryoyas
    - kenkensonson
    - YoshiakiYamasaki
    - kumasan368
    - gakumura
    - yoichiro0217
    # - eminamin
    - TomokoKonishi
    - nonkyon
    - shukawam
    - Kyohei-Git
    - snakane
    - tnagakub
    - taekohayashi
    - yuarashi
    - s-nori
    - ntajima-jp
    - hsakurag
    - yuuur
    - jennylia3
    - sji-cho
    - sshatari
    - yobaya
    - fwiw6430
    - knagasue
    - fukuora
    - mai112233
    - r-deguchi
    - yohono
    - takumiya0824
    - k-yamakawa
    - ora-takahnak
'.github/**':
    - tniita
    - mmarukaw
    - shukawam
    - cyberblack28
    - nonkyon
'**/**':
    - tniita
    - mmarukaw
    - shukawam
    - cyberblack28
    - nonkyon

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false

  # Randomly pick reviewers up to this number.
  # Do not set this option if you'd like to assign all matching reviewers.
  number_of_reviewers: 2